version: "3.9"
services:
  php:
    container_name: event-sourcing-message-bus-php
    build:
      context: .docker/php
      dockerfile: Dockerfile
    links:
      - database
      - message-bus
    volumes:
      - .:/usr/src/app

###> doctrine/doctrine-bundle ###
  database:
    container_name: event-sourcing-message-bus-database
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      PGDATA: /var/lib/postgresql/data/pgdata
#    ports:
#      - 32771:5432
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql:rw
###< doctrine/doctrine-bundle ###

  message-bus:
    container_name: message-bus
    image: rabbitmq:3
    hostname: message-bus

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
    driver: local

###< doctrine/doctrine-bundle ###
